"""
backend_x86.py — x86-64 code generation backend

Calling convention: System V AMD64 ABI (Linux/macOS)
  Integer args:   rdi, rsi, rdx, rcx, r8, r9
  Float args:     xmm0–xmm7
  Return value:   rax (integer), xmm0 (float)
  Callee-saved:   rbx, rbp, r12–r15
  Caller-saved:   rax, rcx, rdx, rsi, rdi, r8–r11

Output syntax: Intel (dst, src order — cleaner to read)
"""

from backend import Backend, RegisterAllocator
from ir import IRInstr, IROp, IRType, VReg, Immediate, LabelRef, IRFunction, IRModule


class X86Backend(Backend):
    name = "x86-64"

    # Caller-saved general purpose registers — used as virtual reg pool
    INT_REGS = [
        "rax", "rcx", "rdx", "rsi", "rdi",
        "r8",  "r9",  "r10", "r11",
        "rbx", "r12", "r13", "r14", "r15",   # callee-saved but usable
    ]

    FLOAT_REGS = [f"xmm{i}" for i in range(16)]

    # -----------------------------------------------------------------------
    # File / section structure
    # -----------------------------------------------------------------------

    def file_header(self) -> str:
        return (
            "; Generated by portable-asm compiler — x86-64 target\n"
            "bits 64\n"
            "default rel\n"
        )

    def text_section_header(self) -> str:
        return "section .text"

    def data_section_header(self) -> str:
        return "section .data"

    def emit_global(self, instr) -> str:
        if instr.srcs:
            imm = instr.srcs[0]
            type_map = {
                IRType.U8:  ("db", 1),
                IRType.U16: ("dw", 2),
                IRType.U32: ("dd", 4),
                IRType.U64: ("dq", 8),
                IRType.I32: ("dd", 4),
                IRType.I64: ("dq", 8),
            }
            directive, _ = type_map.get(imm.type, ("dq", 8))
            return f"    {directive} {imm.value}"
        return ""

    # -----------------------------------------------------------------------
    # Function prologue / epilogue
    # -----------------------------------------------------------------------

    def fn_prologue(self, name: str, frame_size: int) -> str:
        lines = [
            f"global {name}",
            "    push    rbp",
            "    mov     rbp, rsp",
        ]
        if frame_size > 0:
            # Align to 16 bytes
            aligned = (frame_size + 15) & ~15
            lines.append(f"    sub     rsp, {aligned}")
        return "\n".join(lines)

    def fn_epilogue(self, name: str) -> str:
        return ""   # ret instruction is emitted by IROp.RET handler

    # -----------------------------------------------------------------------
    # Instruction emission
    # -----------------------------------------------------------------------

    def emit_instr(self, instr: IRInstr, alloc: RegisterAllocator) -> str:
        op = instr.op

        def dst():
            return alloc.resolve(instr.dst)

        def src(i):
            return alloc.resolve(instr.srcs[i])

        # -- Data movement --
        if op == IROp.COPY:
            return self._i(f"mov     {dst()}, {src(0)}")

        if op == IROp.LEA:
            return self._i(f"lea     {dst()}, [{instr.label}]")

        # -- Arithmetic --
        if op == IROp.ADD:
            return self._two_op("add", dst(), src(0), src(1))

        if op == IROp.SUB:
            return self._two_op("sub", dst(), src(0), src(1))

        if op == IROp.MUL:
            # imul supports three-operand form
            return self._i(f"imul    {dst()}, {src(0)}, {src(1)}"
                           if self._is_imm(instr.srcs[1])
                           else f"imul    {dst()}, {src(0)}")

        if op == IROp.DIV:
            # idiv uses rax:rdx implicitly — emit a sequence
            lines = [
                self._i(f"mov     rax, {src(0)}"),
                self._i("cqo"),                        # sign-extend rax → rdx:rax
                self._i(f"idiv    {src(1)}"),
                self._i(f"mov     {dst()}, rax"),      # quotient in rax
            ]
            return "\n".join(lines)

        if op == IROp.MOD:
            lines = [
                self._i(f"mov     rax, {src(0)}"),
                self._i("cqo"),
                self._i(f"idiv    {src(1)}"),
                self._i(f"mov     {dst()}, rdx"),      # remainder in rdx
            ]
            return "\n".join(lines)

        # -- Bitwise --
        if op == IROp.AND:
            return self._two_op("and", dst(), src(0), src(1))

        if op == IROp.OR:
            return self._two_op("or", dst(), src(0), src(1))

        if op == IROp.XOR:
            return self._two_op("xor", dst(), src(0), src(1))

        if op == IROp.NOT:
            lines = [
                self._i(f"mov     {dst()}, {src(0)}"),
                self._i(f"not     {dst()}"),
            ]
            return "\n".join(lines)

        if op == IROp.SHL:
            return self._shift("shl", dst(), src(0), src(1))

        if op == IROp.SHR:
            return self._shift("shr", dst(), src(0), src(1))

        if op == IROp.SAR:
            return self._shift("sar", dst(), src(0), src(1))

        # -- Comparison --
        if op == IROp.CMP:
            lines = [
                self._i(f"cmp     {src(0)}, {src(1)}"),
                self._i(f"sete    al"),
                self._i(f"movzx   {dst()}, al"),
            ]
            return "\n".join(lines)

        # -- Memory --
        if op == IROp.LOAD:
            base   = src(0)
            offset = instr.srcs[1].value if len(instr.srcs) > 1 else 0
            addr   = f"[{base}]" if offset == 0 else f"[{base}+{offset}]"
            return self._i(f"mov     {dst()}, {addr}")

        if op == IROp.STORE:
            base   = src(0)
            offset = instr.srcs[1].value if len(instr.srcs) > 1 else 0
            value  = src(2) if len(instr.srcs) > 2 else src(1)
            addr   = f"[{base}]" if offset == 0 else f"[{base}+{offset}]"
            return self._i(f"mov     {addr}, {value}")

        # -- Stack --
        if op == IROp.PUSH:
            return self._i(f"push    {src(0)}")

        if op == IROp.POP:
            return self._i(f"pop     {dst()}")

        # -- Control flow --
        if op == IROp.CALL:
            fn_ref  = src(0)
            # Move args into calling convention registers
            arg_regs = ["rdi", "rsi", "rdx", "rcx", "r8", "r9"]
            lines = []
            for i, arg in enumerate(instr.srcs[1:]):
                if i < len(arg_regs):
                    lines.append(self._i(f"mov     {arg_regs[i]}, {alloc.resolve(arg)}"))
            lines.append(self._i(f"call    {fn_ref}"))
            if instr.dst:
                lines.append(self._i(f"mov     {dst()}, rax"))
            return "\n".join(lines)

        if op == IROp.RET:
            lines = []
            if instr.srcs:
                lines.append(self._i(f"mov     rax, {src(0)}"))
            lines += [
                self._i("mov     rsp, rbp"),
                self._i("pop     rbp"),
                self._i("ret"),
            ]
            return "\n".join(lines)

        if op == IROp.JMP:
            return self._i(f"jmp     {instr.label}")

        if op == IROp.JIF:
            # label2 encodes the condition kind (je, jne, etc.)
            cond_map = {
                'je':  'je',  'jne': 'jne',
                'jlt': 'jl',  'jle': 'jle',
                'jgt': 'jg',  'jge': 'jge',
            }
            mnemonic = cond_map.get(instr.label2, 'je')
            return self._i(f"{mnemonic:<8}{instr.label}")

        if op == IROp.NOP:
            return self._i("nop")

        if op == IROp.HLT:
            return self._i("hlt")

        return f"    ; [unhandled op: {op}]"

    # -----------------------------------------------------------------------
    # Helpers
    # -----------------------------------------------------------------------

    def _i(self, s: str) -> str:
        return "    " + s

    def _is_imm(self, val) -> bool:
        return isinstance(val, Immediate)

    def _two_op(self, mnemonic: str, dst: str, src1: str, src2: str) -> str:
        """Emit a two-operand instruction, handling the case where dst != src1."""
        if dst == src1:
            return self._i(f"{mnemonic:<8}{dst}, {src2}")
        else:
            return "\n".join([
                self._i(f"mov     {dst}, {src1}"),
                self._i(f"{mnemonic:<8}{dst}, {src2}"),
            ])

    def _shift(self, mnemonic: str, dst: str, src1: str, amount: str) -> str:
        """x86 shifts: amount must be in cl or an immediate."""
        lines = []
        if dst != src1:
            lines.append(self._i(f"mov     {dst}, {src1}"))
        # If amount is not an immediate, move it to cl
        try:
            int(amount)   # will succeed for immediate strings
            lines.append(self._i(f"{mnemonic:<8}{dst}, {amount}"))
        except ValueError:
            lines.append(self._i(f"mov     rcx, {amount}"))
            lines.append(self._i(f"{mnemonic:<8}{dst}, cl"))
        return "\n".join(lines)
