"""
backend_riscv.py — RISC-V RV64GC code generation backend

Calling convention: RISC-V ELF psABI
  Integer args:   a0–a7  (x10–x17)
  Float args:     fa0–fa7
  Return value:   a0/a1  (integer),  fa0/fa1 (float)
  Callee-saved:   s0–s11 (x8–x9, x18–x27), sp (x2), ra (x1)
  Caller-saved:   ra, t0–t6, a0–a7

Register aliases used here:
  zero = x0   (always zero)
  ra   = x1   (return address)
  sp   = x2   (stack pointer)
  fp   = x8   (frame pointer / s0)
  a0–a7        argument / return registers
  t0–t6        temporaries
  s1–s11       saved registers
"""

from backend import Backend, RegisterAllocator
from ir import IRInstr, IROp, IRType, VReg, Immediate, LabelRef


class RISCVBackend(Backend):
    name = "riscv64"

    INT_REGS = [
        "a0", "a1", "a2", "a3", "a4", "a5", "a6", "a7",
        "t0", "t1", "t2", "t3", "t4", "t5", "t6",
        "s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8", "s9", "s10", "s11",
    ]

    FLOAT_REGS = [f"fa{i}" for i in range(8)] + [f"ft{i}" for i in range(12)]

    # -----------------------------------------------------------------------
    # File / section structure
    # -----------------------------------------------------------------------

    def file_header(self) -> str:
        return (
            "# Generated by portable-asm compiler — RISC-V RV64GC target\n"
            ".option pic\n"
        )

    def text_section_header(self) -> str:
        return ".section .text\n.align 2"

    def data_section_header(self) -> str:
        return ".section .data"

    def emit_global(self, instr) -> str:
        if instr.srcs:
            imm = instr.srcs[0]
            directive_map = {
                IRType.U8:  ".byte",
                IRType.U16: ".half",
                IRType.U32: ".word",
                IRType.U64: ".dword",
                IRType.I32: ".word",
                IRType.I64: ".dword",
            }
            d = directive_map.get(imm.type, ".dword")
            return f"    {d} {imm.value}"
        return ""

    # -----------------------------------------------------------------------
    # Function prologue / epilogue
    # -----------------------------------------------------------------------

    def fn_prologue(self, name: str, frame_size: int) -> str:
        aligned = max(16, (frame_size + 15) & ~15)
        lines = [
            f".global {name}",
            f"    addi    sp, sp, -{aligned}",
            f"    sd      ra, {aligned-8}(sp)",
            f"    sd      fp, {aligned-16}(sp)",
            f"    addi    fp, sp, {aligned}",
        ]
        return "\n".join(lines)

    def fn_epilogue(self, name: str) -> str:
        return ""   # emitted by RET handler

    # -----------------------------------------------------------------------
    # Instruction emission
    # -----------------------------------------------------------------------

    def emit_instr(self, instr: IRInstr, alloc: RegisterAllocator) -> str:
        op = instr.op

        def dst():
            return alloc.resolve(instr.dst)

        def src(i):
            return alloc.resolve(instr.srcs[i])

        def is_imm(i):
            return isinstance(instr.srcs[i], Immediate)

        def imm_val(i):
            return instr.srcs[i].value

        # -- Data movement --
        if op == IROp.COPY:
            v = instr.srcs[0]
            if isinstance(v, Immediate):
                return self._i(f"li      {dst()}, {v.value}")
            return self._i(f"mv      {dst()}, {src(0)}")

        if op == IROp.LEA:
            return "\n".join([
                self._i(f"la      {dst()}, {instr.label}"),
            ])

        # -- Arithmetic --
        if op == IROp.ADD:
            if is_imm(1):
                return self._i(f"addi    {dst()}, {src(0)}, {imm_val(1)}")
            return self._i(f"add     {dst()}, {src(0)}, {src(1)}")

        if op == IROp.SUB:
            if is_imm(1):
                # RISC-V has no subi — use addi with negated immediate
                return self._i(f"addi    {dst()}, {src(0)}, -{imm_val(1)}")
            return self._i(f"sub     {dst()}, {src(0)}, {src(1)}")

        if op == IROp.MUL:
            return self._i(f"mul     {dst()}, {src(0)}, {src(1)}")

        if op == IROp.DIV:
            return self._i(f"div     {dst()}, {src(0)}, {src(1)}")

        if op == IROp.MOD:
            return self._i(f"rem     {dst()}, {src(0)}, {src(1)}")

        # -- Bitwise --
        if op == IROp.AND:
            if is_imm(1):
                return self._i(f"andi    {dst()}, {src(0)}, {imm_val(1)}")
            return self._i(f"and     {dst()}, {src(0)}, {src(1)}")

        if op == IROp.OR:
            if is_imm(1):
                return self._i(f"ori     {dst()}, {src(0)}, {imm_val(1)}")
            return self._i(f"or      {dst()}, {src(0)}, {src(1)}")

        if op == IROp.XOR:
            if is_imm(1):
                return self._i(f"xori    {dst()}, {src(0)}, {imm_val(1)}")
            return self._i(f"xor     {dst()}, {src(0)}, {src(1)}")

        if op == IROp.NOT:
            # RISC-V: not rd, rs  →  xori rd, rs, -1
            return self._i(f"not     {dst()}, {src(0)}")

        if op == IROp.SHL:
            if is_imm(1):
                return self._i(f"slli    {dst()}, {src(0)}, {imm_val(1)}")
            return self._i(f"sll     {dst()}, {src(0)}, {src(1)}")

        if op == IROp.SHR:
            if is_imm(1):
                return self._i(f"srli    {dst()}, {src(0)}, {imm_val(1)}")
            return self._i(f"srl     {dst()}, {src(0)}, {src(1)}")

        if op == IROp.SAR:
            if is_imm(1):
                return self._i(f"srai    {dst()}, {src(0)}, {imm_val(1)}")
            return self._i(f"sra     {dst()}, {src(0)}, {src(1)}")

        # -- Comparison --
        if op == IROp.CMP:
            # Emit slt (set less than) — generalised comparison
            lines = [
                self._i(f"sub     {dst()}, {src(0)}, {src(1)}"),
                self._i(f"seqz    {dst()}, {dst()}"),
            ]
            return "\n".join(lines)

        # -- Memory --
        if op == IROp.LOAD:
            base   = src(0)
            offset = instr.srcs[1].value if len(instr.srcs) > 1 else 0
            return self._i(f"ld      {dst()}, {offset}({base})")

        if op == IROp.STORE:
            base   = src(0)
            offset = instr.srcs[1].value if len(instr.srcs) > 1 else 0
            value  = src(2) if len(instr.srcs) > 2 else src(1)
            return self._i(f"sd      {value}, {offset}({base})")

        # -- Stack --
        if op == IROp.PUSH:
            lines = [
                self._i(f"addi    sp, sp, -8"),
                self._i(f"sd      {src(0)}, 0(sp)"),
            ]
            return "\n".join(lines)

        if op == IROp.POP:
            lines = [
                self._i(f"ld      {dst()}, 0(sp)"),
                self._i(f"addi    sp, sp, 8"),
            ]
            return "\n".join(lines)

        # -- Control flow --
        if op == IROp.CALL:
            fn_ref   = src(0)
            arg_regs = [f"a{i}" for i in range(8)]
            lines    = []
            for i, arg in enumerate(instr.srcs[1:]):
                if i < len(arg_regs):
                    resolved = alloc.resolve(arg)
                    if resolved != arg_regs[i]:
                        lines.append(self._i(f"mv      {arg_regs[i]}, {resolved}"))
            lines.append(self._i(f"call    {fn_ref}"))
            if instr.dst:
                lines.append(self._i(f"mv      {dst()}, a0"))
            return "\n".join(lines)

        if op == IROp.RET:
            frame_size = 16
            lines = []
            if instr.srcs:
                lines.append(self._i(f"mv      a0, {src(0)}"))
            lines += [
                self._i(f"ld      ra, {frame_size-8}(sp)"),
                self._i(f"ld      fp, {frame_size-16}(sp)"),
                self._i(f"addi    sp, sp, {frame_size}"),
                self._i("ret"),
            ]
            return "\n".join(lines)

        if op == IROp.JMP:
            return self._i(f"j       {instr.label}")

        if op == IROp.JIF:
            cond_map = {
                'je':  ('beq',  'zero'),
                'jne': ('bnez', None),
                'jlt': ('bltz', None),
                'jle': ('blez', None),
                'jgt': ('bgtz', None),
                'jge': ('bgez', None),
            }
            entry = cond_map.get(instr.label2, ('bnez', None))
            mnem, extra = entry
            cond_reg = alloc.resolve(instr.srcs[0])
            if extra:
                return self._i(f"{mnem:<8}{cond_reg}, {extra}, {instr.label}")
            return self._i(f"{mnem:<8}{cond_reg}, {instr.label}")

        if op == IROp.NOP:
            return self._i("nop")

        if op == IROp.HLT:
            return self._i("ebreak")

        return f"    # [unhandled op: {op}]"

    def _i(self, s: str) -> str:
        return "    " + s
