"""
backend_arm64.py — AArch64 (ARM64) code generation backend

Calling convention: AAPCS64
  Integer args:   x0–x7
  Float args:     v0–v7
  Return value:   x0 (integer), v0 (float)
  Callee-saved:   x19–x28, x29 (fp), x30 (lr)
  Caller-saved:   x0–x18

Register naming:
  x0–x30   64-bit general purpose
  w0–w30   32-bit aliases of x0–x30
  sp       stack pointer
  xzr/wzr  zero register
  v0–v31   SIMD/FP registers
"""

from backend import Backend, RegisterAllocator
from ir import IRInstr, IROp, IRType, VReg, Immediate, LabelRef


class ARM64Backend(Backend):
    name = "arm64"

    INT_REGS = [
        "x0",  "x1",  "x2",  "x3",  "x4",  "x5",  "x6",  "x7",
        "x9",  "x10", "x11", "x12", "x13", "x14", "x15",
        "x19", "x20", "x21", "x22", "x23", "x24", "x25", "x26", "x27", "x28",
    ]

    FLOAT_REGS = [f"d{i}" for i in range(32)]

    # -----------------------------------------------------------------------
    # File / section structure
    # -----------------------------------------------------------------------

    def file_header(self) -> str:
        return (
            "; Generated by portable-asm compiler — AArch64 target\n"
            ".arch armv8-a\n"
        )

    def text_section_header(self) -> str:
        return ".section __TEXT,__text,regular,pure_instructions\n.align 2"

    def data_section_header(self) -> str:
        return ".section __DATA,__data"

    def emit_global(self, instr) -> str:
        if instr.srcs:
            imm = instr.srcs[0]
            directive_map = {
                IRType.U8:  ".byte",
                IRType.U16: ".short",
                IRType.U32: ".long",
                IRType.U64: ".quad",
                IRType.I32: ".long",
                IRType.I64: ".quad",
            }
            d = directive_map.get(imm.type, ".quad")
            return f"    {d} {imm.value}"
        return ""

    # -----------------------------------------------------------------------
    # Function prologue / epilogue
    # -----------------------------------------------------------------------

    def fn_prologue(self, name: str, frame_size: int) -> str:
        aligned = max(16, (frame_size + 15) & ~15)
        lines = [
            f".global {name}",
            f"    stp     x29, x30, [sp, #-{aligned}]!",   # save fp + lr
            f"    mov     x29, sp",                          # set frame pointer
        ]
        return "\n".join(lines)

    def fn_epilogue(self, name: str) -> str:
        return ""   # emitted by RET handler

    # -----------------------------------------------------------------------
    # Instruction emission
    # -----------------------------------------------------------------------

    def emit_instr(self, instr: IRInstr, alloc: RegisterAllocator) -> str:
        op = instr.op

        def dst():
            return alloc.resolve(instr.dst)

        def src(i):
            return alloc.resolve(instr.srcs[i])

        def imm_or_reg(i):
            """ARM64 immediate operands use # prefix."""
            v = instr.srcs[i]
            if isinstance(v, Immediate):
                return f"#{v.value}"
            return alloc.resolve(v)

        # -- Data movement --
        if op == IROp.COPY:
            v = instr.srcs[0]
            if isinstance(v, Immediate):
                return self._i(f"mov     {dst()}, #{v.value}")
            return self._i(f"mov     {dst()}, {src(0)}")

        if op == IROp.LEA:
            return self._i(f"adrp    {dst()}, {instr.label}@PAGE\n"
                           f"    add     {dst()}, {dst()}, {instr.label}@PAGEOFF")

        # -- Arithmetic --
        if op == IROp.ADD:
            return self._i(f"add     {dst()}, {src(0)}, {imm_or_reg(1)}")

        if op == IROp.SUB:
            return self._i(f"sub     {dst()}, {src(0)}, {imm_or_reg(1)}")

        if op == IROp.MUL:
            return self._i(f"mul     {dst()}, {src(0)}, {src(1)}")

        if op == IROp.DIV:
            signed = True   # default signed
            mnemonic = "sdiv" if signed else "udiv"
            return self._i(f"{mnemonic}   {dst()}, {src(0)}, {src(1)}")

        if op == IROp.MOD:
            # ARM64 has no mod instruction — compute as: mod = a - (a/b)*b
            tmp = dst()
            lines = [
                self._i(f"sdiv    {tmp}, {src(0)}, {src(1)}"),
                self._i(f"msub    {dst()}, {tmp}, {src(1)}, {src(0)}"),
            ]
            return "\n".join(lines)

        # -- Bitwise --
        if op == IROp.AND:
            return self._i(f"and     {dst()}, {src(0)}, {imm_or_reg(1)}")

        if op == IROp.OR:
            return self._i(f"orr     {dst()}, {src(0)}, {imm_or_reg(1)}")

        if op == IROp.XOR:
            return self._i(f"eor     {dst()}, {src(0)}, {imm_or_reg(1)}")

        if op == IROp.NOT:
            return self._i(f"mvn     {dst()}, {src(0)}")

        if op == IROp.SHL:
            return self._i(f"lsl     {dst()}, {src(0)}, {imm_or_reg(1)}")

        if op == IROp.SHR:
            return self._i(f"lsr     {dst()}, {src(0)}, {imm_or_reg(1)}")

        if op == IROp.SAR:
            return self._i(f"asr     {dst()}, {src(0)}, {imm_or_reg(1)}")

        # -- Comparison --
        if op == IROp.CMP:
            lines = [
                self._i(f"cmp     {src(0)}, {imm_or_reg(1)}"),
                self._i(f"cset    {dst()}, eq"),
            ]
            return "\n".join(lines)

        # -- Memory --
        if op == IROp.LOAD:
            base   = src(0)
            offset = instr.srcs[1].value if len(instr.srcs) > 1 else 0
            if offset == 0:
                return self._i(f"ldr     {dst()}, [{base}]")
            return self._i(f"ldr     {dst()}, [{base}, #{offset}]")

        if op == IROp.STORE:
            base   = src(0)
            offset = instr.srcs[1].value if len(instr.srcs) > 1 else 0
            value  = src(2) if len(instr.srcs) > 2 else src(1)
            if offset == 0:
                return self._i(f"str     {value}, [{base}]")
            return self._i(f"str     {value}, [{base}, #{offset}]")

        # -- Stack --
        if op == IROp.PUSH:
            return self._i(f"str     {src(0)}, [sp, #-8]!")

        if op == IROp.POP:
            return self._i(f"ldr     {dst()}, [sp], #8")

        # -- Control flow --
        if op == IROp.CALL:
            fn_ref   = src(0)
            arg_regs = [f"x{i}" for i in range(8)]
            lines    = []
            for i, arg in enumerate(instr.srcs[1:]):
                if i < len(arg_regs):
                    resolved = alloc.resolve(arg)
                    if resolved != arg_regs[i]:
                        lines.append(self._i(f"mov     {arg_regs[i]}, {resolved}"))
            lines.append(self._i(f"bl      {fn_ref}"))
            if instr.dst:
                lines.append(self._i(f"mov     {dst()}, x0"))
            return "\n".join(lines)

        if op == IROp.RET:
            frame_size = 16   # minimum frame from prologue
            lines = []
            if instr.srcs:
                lines.append(self._i(f"mov     x0, {src(0)}"))
            lines += [
                self._i(f"ldp     x29, x30, [sp], #{frame_size}"),
                self._i("ret"),
            ]
            return "\n".join(lines)

        if op == IROp.JMP:
            return self._i(f"b       {instr.label}")

        if op == IROp.JIF:
            cond_map = {
                'je':  'eq', 'jne': 'ne',
                'jlt': 'lt', 'jle': 'le',
                'jgt': 'gt', 'jge': 'ge',
            }
            cond = cond_map.get(instr.label2, 'eq')
            return self._i(f"b.{cond:<5}  {instr.label}")

        if op == IROp.NOP:
            return self._i("nop")

        if op == IROp.HLT:
            return self._i("brk     #0")

        return f"    ; [unhandled op: {op}]"

    def _i(self, s: str) -> str:
        return "    " + s
