
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AT COLON COMMA DIRECTIVE FLOAT_LIT HASH IDENT INT_LIT LANGLE LBRACKET MINUS NEWLINE OPCODE PLUS RANGLE RBRACKET REGISTER STRING_LIT TYPEprogram : statement_liststatement_list : statement_list statement\n| statement\n| statement_list NEWLINE\n| NEWLINEstatement : directivestatement : label_defstatement : instructiondirective : DIRECTIVE IDENT\n| DIRECTIVE DIRECTIVE\n| DIRECTIVEdirective : DIRECTIVE IDENT COMMA AT IDENTlabel_def : IDENT COLON type_expr COLONlabel_def : IDENT COLONinstruction : OPCODE operand_listinstruction : OPCODEoperand_list : operand_list COMMA operand\n| operandoperand : REGISTER COLON type_expr\n| REGISTERoperand : HASH INT_LIT COLON type_expr\n| HASH INT_LIToperand : HASH MINUS INT_LIT COLON type_expr\n| HASH MINUS INT_LIToperand : LBRACKET REGISTER PLUS  INT_LIT RBRACKET COLON type_expr\n| LBRACKET REGISTER MINUS INT_LIT RBRACKET COLON type_expr\n| LBRACKET REGISTER PLUS  INT_LIT RBRACKET\n| LBRACKET REGISTER MINUS INT_LIT RBRACKEToperand : LBRACKET REGISTER RBRACKET COLON type_expr\n| LBRACKET REGISTER RBRACKEToperand : IDENTtype_expr : TYPEtype_expr : TYPE LANGLE type_expr RANGLE'
    
_lr_action_items = {'NEWLINE':([0,2,3,4,5,6,7,8,10,11,12,13,14,15,16,17,18,21,24,27,31,33,34,36,38,40,42,47,48,49,50,51,54,55,],[4,12,-3,-5,-6,-7,-8,-11,-16,-2,-4,-10,-9,-14,-15,-18,-20,-31,-32,-22,-13,-17,-19,-24,-30,-12,-21,-33,-23,-27,-29,-28,-25,-26,]),'DIRECTIVE':([0,2,3,4,5,6,7,8,10,11,12,13,14,15,16,17,18,21,24,27,31,33,34,36,38,40,42,47,48,49,50,51,54,55,],[8,8,-3,-5,-6,-7,-8,13,-16,-2,-4,-10,-9,-14,-15,-18,-20,-31,-32,-22,-13,-17,-19,-24,-30,-12,-21,-33,-23,-27,-29,-28,-25,-26,]),'IDENT':([0,2,3,4,5,6,7,8,10,11,12,13,14,15,16,17,18,21,24,25,27,30,31,33,34,36,38,40,42,47,48,49,50,51,54,55,],[9,9,-3,-5,-6,-7,-8,14,21,-2,-4,-10,-9,-14,-15,-18,-20,-31,-32,21,-22,40,-13,-17,-19,-24,-30,-12,-21,-33,-23,-27,-29,-28,-25,-26,]),'OPCODE':([0,2,3,4,5,6,7,8,10,11,12,13,14,15,16,17,18,21,24,27,31,33,34,36,38,40,42,47,48,49,50,51,54,55,],[10,10,-3,-5,-6,-7,-8,-11,-16,-2,-4,-10,-9,-14,-15,-18,-20,-31,-32,-22,-13,-17,-19,-24,-30,-12,-21,-33,-23,-27,-29,-28,-25,-26,]),'$end':([1,2,3,4,5,6,7,8,10,11,12,13,14,15,16,17,18,21,24,27,31,33,34,36,38,40,42,47,48,49,50,51,54,55,],[0,-1,-3,-5,-6,-7,-8,-11,-16,-2,-4,-10,-9,-14,-15,-18,-20,-31,-32,-22,-13,-17,-19,-24,-30,-12,-21,-33,-23,-27,-29,-28,-25,-26,]),'COLON':([9,18,23,24,27,36,38,47,49,51,],[15,26,31,-32,35,43,45,-33,52,53,]),'REGISTER':([10,20,25,],[18,29,18,]),'HASH':([10,25,],[19,19,]),'LBRACKET':([10,25,],[20,20,]),'COMMA':([14,16,17,18,21,24,27,33,34,36,38,42,47,48,49,50,51,54,55,],[22,25,-18,-20,-31,-32,-22,-17,-19,-24,-30,-21,-33,-23,-27,-29,-28,-25,-26,]),'TYPE':([15,26,32,35,43,45,52,53,],[24,24,24,24,24,24,24,24,]),'INT_LIT':([19,28,37,39,],[27,36,44,46,]),'MINUS':([19,29,],[28,39,]),'AT':([22,],[30,]),'RANGLE':([24,41,47,],[-32,47,-33,]),'LANGLE':([24,],[32,]),'PLUS':([29,],[37,]),'RBRACKET':([29,44,46,],[38,49,51,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement_list':([0,],[2,]),'statement':([0,2,],[3,11,]),'directive':([0,2,],[5,5,]),'label_def':([0,2,],[6,6,]),'instruction':([0,2,],[7,7,]),'operand_list':([10,],[16,]),'operand':([10,25,],[17,33,]),'type_expr':([15,26,32,35,43,45,52,53,],[23,34,41,42,48,50,54,55,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement_list','program',1,'p_program','parser.py',74),
  ('statement_list -> statement_list statement','statement_list',2,'p_statement_list','parser.py',79),
  ('statement_list -> statement','statement_list',1,'p_statement_list','parser.py',80),
  ('statement_list -> statement_list NEWLINE','statement_list',2,'p_statement_list','parser.py',81),
  ('statement_list -> NEWLINE','statement_list',1,'p_statement_list','parser.py',82),
  ('statement -> directive','statement',1,'p_statement_directive','parser.py',87),
  ('statement -> label_def','statement',1,'p_statement_label','parser.py',93),
  ('statement -> instruction','statement',1,'p_statement_instruction','parser.py',99),
  ('directive -> DIRECTIVE IDENT','directive',2,'p_directive_section','parser.py',109),
  ('directive -> DIRECTIVE DIRECTIVE','directive',2,'p_directive_section','parser.py',110),
  ('directive -> DIRECTIVE','directive',1,'p_directive_section','parser.py',111),
  ('directive -> DIRECTIVE IDENT COMMA AT IDENT','directive',5,'p_directive_two_args','parser.py',129),
  ('label_def -> IDENT COLON type_expr COLON','label_def',4,'p_label_def_typed','parser.py',138),
  ('label_def -> IDENT COLON','label_def',2,'p_label_def','parser.py',143),
  ('instruction -> OPCODE operand_list','instruction',2,'p_instruction_with_operands','parser.py',152),
  ('instruction -> OPCODE','instruction',1,'p_instruction_no_operands','parser.py',157),
  ('operand_list -> operand_list COMMA operand','operand_list',3,'p_operand_list','parser.py',162),
  ('operand_list -> operand','operand_list',1,'p_operand_list','parser.py',163),
  ('operand -> REGISTER COLON type_expr','operand',3,'p_operand_register','parser.py',175),
  ('operand -> REGISTER','operand',1,'p_operand_register','parser.py',176),
  ('operand -> HASH INT_LIT COLON type_expr','operand',4,'p_operand_immediate_pos','parser.py',182),
  ('operand -> HASH INT_LIT','operand',2,'p_operand_immediate_pos','parser.py',183),
  ('operand -> HASH MINUS INT_LIT COLON type_expr','operand',5,'p_operand_immediate_neg','parser.py',189),
  ('operand -> HASH MINUS INT_LIT','operand',3,'p_operand_immediate_neg','parser.py',190),
  ('operand -> LBRACKET REGISTER PLUS INT_LIT RBRACKET COLON type_expr','operand',7,'p_operand_mem_with_offset','parser.py',196),
  ('operand -> LBRACKET REGISTER MINUS INT_LIT RBRACKET COLON type_expr','operand',7,'p_operand_mem_with_offset','parser.py',197),
  ('operand -> LBRACKET REGISTER PLUS INT_LIT RBRACKET','operand',5,'p_operand_mem_with_offset','parser.py',198),
  ('operand -> LBRACKET REGISTER MINUS INT_LIT RBRACKET','operand',5,'p_operand_mem_with_offset','parser.py',199),
  ('operand -> LBRACKET REGISTER RBRACKET COLON type_expr','operand',5,'p_operand_mem_no_offset','parser.py',207),
  ('operand -> LBRACKET REGISTER RBRACKET','operand',3,'p_operand_mem_no_offset','parser.py',208),
  ('operand -> IDENT','operand',1,'p_operand_label_ref','parser.py',214),
  ('type_expr -> TYPE','type_expr',1,'p_type_expr_base','parser.py',223),
  ('type_expr -> TYPE LANGLE type_expr RANGLE','type_expr',4,'p_type_expr_ptr','parser.py',228),
]
