import { useState, useRef } from 'react';

const DEMO_CODE = `.section .text
.global main

; Compute sum = a + b, store it, then return it
main:
    mov   r0:i64, #10
    mov   r1:i64, #32
    add   r2:i64, r0:i64, r1:i64
    push  r2
    call  print_int
    pop   r2
    ret   r2
`;

export default function App() {
  const [sourceCode, setSourceCode] = useState('');
  const [targetArch, setTargetArch] = useState('x86-64');
  const [compiledAsm, setCompiledAsm] = useState('');
  const [logs, setLogs] = useState<string[]>(['System initialized.']);
  const [isCompiling, setIsCompiling] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const addLog = (msg: string) => {
    const time = new Date().toLocaleTimeString([], { hour12: false });
    setLogs(prev => [...prev, `[${time}] ${msg}`]);
  };

  const handleLoadDemo = () => {
    setSourceCode(DEMO_CODE);
    addLog('Demo loaded.');
    setCompiledAsm('');
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      setSourceCode(event.target?.result as string);
      addLog(`File '${file.name}' loaded successfully.`);
      setCompiledAsm('');
    };
    reader.onerror = () => addLog('Error reading file.');
    reader.readAsText(file);
    
    // Reset input
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  const handleCompile = async () => {
    if (!sourceCode.trim()) {
      addLog('Error: Please provide source code to compile.');
      return;
    }

    setIsCompiling(true);
    addLog(`Backend: Target ${targetArch} selected. Emitting module...`);
    
    setTimeout(() => {
      try {
        let lines = sourceCode.split('\n');
        let mappedAsm = lines.map(line => `  ; parsed: ${line.trim()}`);
        
        const asmMap: Record<string, string> = {
          'x86-64': 'section .text\nglobal main\n\nmain:\n  push rbp\n  mov rbp, rsp\n',
          'ARM64': '.section __TEXT,__text,regular,pure_instructions\n.align 2\n.global main\n\nmain:\n  stp x29, x30, [sp, #-16]!\n  mov x29, sp\n',
          'RISC-V': '.section .text\n.align 2\n.global main\n\nmain:\n  addi sp, sp, -16\n  sd ra, 8(sp)\n  sd s0, 0(sp)\n  addi s0, sp, 16\n'
        };
        const architectureHeader = `; Generated by VIRAL Mock Backend\n` + (asmMap[targetArch] || '');
        
        setCompiledAsm(architectureHeader + mappedAsm.join('\n'));
        addLog(`Build Success. Target: ${targetArch}`);
      } catch (err: any) {
        addLog(`Error during compilation: ${err.message}`);
      } finally {
        setIsCompiling(false);
      }
    }, 800);
  };

  return (
    <div className="h-screen bg-slate-50 text-slate-900 font-sans flex flex-col overflow-hidden">
      {/* Header Section */}
      <header className="h-16 flex items-center justify-between px-8 bg-white border-b border-slate-200 shrink-0">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 bg-indigo-600 rounded flex items-center justify-center">
            <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"></path></svg>
          </div>
          <div>
            <h1 className="text-lg font-bold tracking-tight text-slate-800">VIRAL</h1>
            <p className="text-xs text-slate-500">Portable Typed Assembly to Target Machine Code</p>
          </div>
        </div>
        <div className="flex items-center gap-4">
          <button className="px-3 py-1.5 text-xs font-medium text-indigo-600 bg-indigo-50 rounded border border-indigo-100 hover:bg-indigo-100 transition-colors">Documentation</button>
          <button className="px-3 py-1.5 text-xs font-medium text-slate-600 bg-slate-100 rounded border border-slate-200">v0.4.2-stable</button>
        </div>
      </header>

      {/* Top Control Bar */}
      <div className="h-14 bg-white border-b border-slate-200 flex items-center px-8 gap-6 shrink-0">
        <div className="flex gap-2">
          <input 
            type="file" 
            accept=".s,.txt,.pasm" 
            ref={fileInputRef} 
            onChange={handleFileUpload} 
            className="hidden" 
            id="file-upload"
          />
          <button 
            onClick={() => fileInputRef.current?.click()}
            className="px-3 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50 border border-slate-200 rounded flex items-center gap-2 transition-colors"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12"></path></svg>
            Upload .s
          </button>
          <button 
            onClick={handleLoadDemo}
            className="px-3 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50 border border-slate-200 rounded flex items-center gap-2 transition-colors"
          >
            <svg className="w-4 h-4 text-indigo-500" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM9.555 7.168A1 1 0 008 8v4a1 1 0 001.555.832l3-2a1 1 0 000-1.664l-3-2z" clipRule="evenodd"></path></svg>
            Load Demo
          </button>
        </div>
        <div className="h-6 w-px bg-slate-200 mx-2"></div>
        <div className="flex items-center gap-3">
          <span className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Target:</span>
          <select 
            value={targetArch}
            onChange={(e) => setTargetArch(e.target.value)}
            className="bg-slate-50 border border-slate-200 rounded text-sm px-2 py-1 outline-none focus:ring-1 focus:ring-indigo-500 cursor-pointer"
          >
            <option value="x86-64">x86-64 (Intel/AMD)</option>
            <option value="ARM64">ARM64 (Apple Silicon/Graviton)</option>
            <option value="RISC-V">RISC-V (Open Standard)</option>
          </select>
        </div>
        <div className="flex-grow"></div>
        <button 
          onClick={handleCompile}
          disabled={isCompiling}
          className="px-8 py-1.5 bg-indigo-600 text-white rounded font-semibold text-sm shadow-sm hover:bg-indigo-700 active:transform active:scale-95 transition-all disabled:opacity-75 disabled:active:scale-100"
        >
          {isCompiling ? 'Compiling...' : 'Compile'}
        </button>
      </div>

      {/* Main Editor Section */}
      <main className="flex-grow flex p-6 gap-6 min-h-0 overflow-hidden">
        {/* Left: Source Editor */}
        <div className="flex-1 flex flex-col min-w-0">
          <div className="flex items-center justify-between mb-2 shrink-0">
            <span className="text-[11px] font-bold text-slate-400 uppercase tracking-widest">Source Code (PTA)</span>
            {/* Note: In a real editor we'd track cursor position, mocked here */}
            <span className="text-[11px] text-slate-400 select-none">Editor</span>
          </div>
          <div className="flex-grow bg-[#1e1e2e] rounded-lg shadow-inner border border-slate-300 p-4 font-mono text-sm overflow-hidden flex flex-col relative">
            <textarea
              value={sourceCode}
              onChange={(e) => setSourceCode(e.target.value)}
              className="absolute inset-x-4 inset-y-4 p-0 text-[#cdd6f4] bg-transparent resize-none outline-none leading-relaxed"
              spellCheck={false}
              placeholder="Type your portable assembly here..."
            />
          </div>
        </div>

        {/* Right: Output Viewer */}
        <div className="flex-1 flex flex-col min-w-0">
          <div className="flex items-center justify-between mb-2 shrink-0">
            <span className="text-[11px] font-bold text-slate-400 uppercase tracking-widest">Compiled Output ({targetArch})</span>
            <button 
              onClick={() => {
                navigator.clipboard.writeText(compiledAsm);
                addLog('Output copied to clipboard.');
              }}
              className="text-indigo-600 text-[11px] font-bold hover:underline transition-colors"
            >
              Copy Output
            </button>
          </div>
          <div className="flex-grow bg-slate-100 rounded-lg shadow-inner border border-slate-200 p-4 font-mono text-sm overflow-hidden flex flex-col relative">
            <textarea
              readOnly
              value={compiledAsm}
              className="absolute inset-x-4 inset-y-4 p-0 text-slate-600 bg-transparent resize-none outline-none leading-relaxed"
              spellCheck={false}
              placeholder="Output will appear here..."
            />
          </div>
        </div>
      </main>

      {/* Bottom: Error & Log Console */}
      <footer className="h-40 shrink-0 border-t border-slate-200 bg-white p-4 flex flex-col">
        <div className="flex items-center gap-2 mb-2 px-2">
          <div className="w-2 h-2 rounded-full bg-emerald-500"></div>
          <span className="text-[11px] font-bold text-slate-500 uppercase tracking-widest">System Log / Console</span>
        </div>
        <div className="flex-grow bg-slate-50 rounded border border-slate-200 p-3 font-mono text-[12px] text-slate-600 overflow-y-auto">
          {logs.map((log, i) => (
            <p key={i} className={`mb-1 ${log.includes('Error') ? 'text-red-500' : log.includes('Success') ? 'text-emerald-600 font-bold' : log.includes('Backend:') ? 'text-indigo-600' : 'text-slate-400'}`}>
              {log}
            </p>
          ))}
        </div>
      </footer>
    </div>
  );
}


